name: Copilot CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Ensure Copilot is installed
        run: |
          if ! command -v copilot &> /dev/null; then
            echo "Installing AWS Copilot..."
            curl -Lo copilot-cli https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
            chmod +x copilot-cli
            sudo mv copilot-cli /usr/local/bin/copilot
          fi
          copilot --version

      - name: Deploy with Copilot
        env:
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
        run: |
          copilot svc deploy --env prod
